### ISSUE TITLE
Emergency responders B Roll

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/av-club#80]
Below you will see a list of dates for search and rescue training. Pick two to attend, we need to get B Roll and photos. When you decide on dates have Brenda Jones reach out for scheduling. Booking this is a high priority, please set it us ASAP when you are back.

**Comment by sebastianebarb** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51fa7a2983e27bb91a2e530a571aac42500e42f5ad8c2da0a42062c80d55b98e30063e937f03a6aa8317b500bf238e4986bebb8a45c9ed3837aa.png)

**Comment by DACole** [comment]
Brenda sent new times but is out today so I will reconnect with her tomorrow to and she is suppose to let me know what the best time to be there later this week will be.

**Comment by DACole** [comment]
Last Email.

Hello Darren,

Here are the general agenda and POCs for next week.  To start with Trench Rescue,  it appears Monday is basically classroom where the next days are hands-on practical and performance.  Do you think you can change your date from 9/24 to 9/26 or 27?  Please see agenda overview below:

Trench Rescue Training - Monday September 24
Lead Instructor: Brookline Fire David Randolph
Moon Island 
16 Moon Island Rd 
Boston, MA

Please ask the security guard for the Fire Academy.  It is the section (dirt road) when you get to the academy.  You will see a stackable connect box infrastructure.

Agenda
The first half of day 1 will be PowerPoint with the second half being an in-depth tool lab. Day two will be wooden shores and pneumatics, both first and second half of the day (Two different ways). Day 3 and especially 4 will be great days for a video because there will be a lot going on. Day 4 is scenario day. 

I would like to say that 3, 4 or both would work for your team. 


Vehicle & Machinery Extrication Training - Friday Sept 28
Lead Instructor:  Boston Fire Lt Santiago Lasa
Schnitzer 
538 Broadway 
Everett, MA entrance on Linden Street

Agenda
Will have more information. Currently the morning portion is PowerPoint (classroom).  I recommend afternoon for this training.

Please let me know.  I will be out of town tomorrow but will be able to address on the weekend.

**Comment by DACole** [comment]
Ill be meeting with Brenda in the morning and she also texted me a few shots from earlier this week. 

Brenda:
Vehicle and Machinery Extrication Training - 9/28, afternoon is the best segment.
8:30am and ends at 4:30pm. One hour lunch is always ~ 12pm for the students.

**Comment by DACole** [comment]
Folder with Fotos
https://drive.google.com/open?id=1D3VtBvZkNyoA7KONJtQqvqgBP8gcdpLs
videos
https://drive.google.com/open?id=1ynOPI399zo7evUBdHn_qSz2sRyMUjNv5

Let me know if you need me to color grade any of these, the originals and the jpegs are in the folder.

I also told Brenda to follow up with me about other cool sessions in the future.
